service: zambdas

frameworkVersion: '3'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, self:custom.defaultStage}

custom:
  defaultStage: local
  serverless-offline:
    reloadHandler: true
    host: 0.0.0.0
    httpPort: 3201
    lambdaPort: 3202
  esbuild:
    minify: false
    sourcemap: linked
    keepNames: true

functions:
  get-appointments:
    handler: src/get-appointments/index.index
    events:
      - http:
          path: zambda/get-appointments/execute
          method: POST
    timeout: 25
    environment:
      AUTH0_ENDPOINT: ${file(./.env/${self:provider.stage}.json):AUTH0_ENDPOINT}
      AUTH0_CLIENT: ${file(./.env/${self:provider.stage}.json):AUTH0_CLIENT}
      AUTH0_SECRET: ${file(./.env/${self:provider.stage}.json):AUTH0_SECRET}
      AUTH0_AUDIENCE: ${file(./.env/${self:provider.stage}.json):AUTH0_AUDIENCE}
      FHIR_API: ${file(./.env/${self:provider.stage}.json):FHIR_API}
      ENVIRONMENT: ${file(./.env/${self:provider.stage}.json):ENVIRONMENT}
      SLACK_CHANNEL_HOOK_URL: ${file(./.env/${self:provider.stage}.json):SLACK_CHANNEL_HOOK_URL}
      SENDGRID_API_KEY: ${file(./.env/${self:provider.stage}.json):SENDGRID_API_KEY}
      SENDGRID_ERROR_EMAIL_TEMPLATE_ID: ${file(./.env/${self:provider.stage}.json):SENDGRID_ERROR_EMAIL_TEMPLATE_ID}
      SENDGRID_EMAIL: ${file(./.env/${self:provider.stage}.json):SENDGRID_EMAIL}
  get-token-for-conversation:
    handler: src/get-token-for-conversation/index.index
    events:
      - http:
          path: zambda/get-token-for-conversation/execute
          method: POST
    timeout: 25
    environment:
      AUTH0_ENDPOINT: ${file(./.env/${self:provider.stage}.json):AUTH0_ENDPOINT}
      AUTH0_CLIENT: ${file(./.env/${self:provider.stage}.json):AUTH0_CLIENT}
      AUTH0_SECRET: ${file(./.env/${self:provider.stage}.json):AUTH0_SECRET}
      MESSAGING_DEVICE_ID: ${file(./.env/${self:provider.stage}.json):MESSAGING_DEVICE_ID}
      MESSAGING_M2M_CLIENT: ${file(./.env/${self:provider.stage}.json):MESSAGING_M2M_CLIENT}
      MESSAGING_M2M_SECRET: ${file(./.env/${self:provider.stage}.json):MESSAGING_M2M_SECRET}
      PROJECT_API: ${file(./.env/${self:provider.stage}.json):PROJECT_API}
      AUTH0_AUDIENCE: ${file(./.env/${self:provider.stage}.json):AUTH0_AUDIENCE}
      ENVIRONMENT: ${file(./.env/${self:provider.stage}.json):ENVIRONMENT}
      SLACK_CHANNEL_HOOK_URL: ${file(./.env/${self:provider.stage}.json):SLACK_CHANNEL_HOOK_URL}
      SENDGRID_API_KEY: ${file(./.env/${self:provider.stage}.json):SENDGRID_API_KEY}
      SENDGRID_ERROR_EMAIL_TEMPLATE_ID: ${file(./.env/${self:provider.stage}.json):SENDGRID_ERROR_EMAIL_TEMPLATE_ID}
      SENDGRID_EMAIL: ${file(./.env/${self:provider.stage}.json):SENDGRID_EMAIL}
  update-user:
    handler: src/update-user/index.index
    events:
      - http:
          path: zambda/update-user/execute
          method: POST
    timeout: 25
    environment:
      AUTH0_ENDPOINT: ${file(./.env/${self:provider.stage}.json):AUTH0_ENDPOINT}
      AUTH0_CLIENT: ${file(./.env/${self:provider.stage}.json):AUTH0_CLIENT}
      AUTH0_SECRET: ${file(./.env/${self:provider.stage}.json):AUTH0_SECRET}
      AUTH0_AUDIENCE: ${file(./.env/${self:provider.stage}.json):AUTH0_AUDIENCE}
      PROJECT_API: ${file(./.env/${self:provider.stage}.json):PROJECT_API}
      FHIR_API: ${file(./.env/${self:provider.stage}.json):FHIR_API}
      ENVIRONMENT: ${file(./.env/${self:provider.stage}.json):ENVIRONMENT}
      SLACK_CHANNEL_HOOK_URL: ${file(./.env/${self:provider.stage}.json):SLACK_CHANNEL_HOOK_URL}
      SENDGRID_API_KEY: ${file(./.env/${self:provider.stage}.json):SENDGRID_API_KEY}
      SENDGRID_ERROR_EMAIL_TEMPLATE_ID: ${file(./.env/${self:provider.stage}.json):SENDGRID_ERROR_EMAIL_TEMPLATE_ID}
      SENDGRID_EMAIL: ${file(./.env/${self:provider.stage}.json):SENDGRID_EMAIL}
  deactivate-user:
    handler: src/deactivate-user/index.index
    events:
      - http:
          path: zambda/deactivate-user/execute
          method: POST
    timeout: 25
    environment:
      AUTH0_ENDPOINT: ${file(./.env/${self:provider.stage}.json):AUTH0_ENDPOINT}
      AUTH0_CLIENT: ${file(./.env/${self:provider.stage}.json):AUTH0_CLIENT}
      AUTH0_SECRET: ${file(./.env/${self:provider.stage}.json):AUTH0_SECRET}
      AUTH0_AUDIENCE: ${file(./.env/${self:provider.stage}.json):AUTH0_AUDIENCE}
      PROJECT_API: ${file(./.env/${self:provider.stage}.json):PROJECT_API}
      FHIR_API: ${file(./.env/${self:provider.stage}.json):FHIR_API}
      ENVIRONMENT: ${file(./.env/${self:provider.stage}.json):ENVIRONMENT}
      SLACK_CHANNEL_HOOK_URL: ${file(./.env/${self:provider.stage}.json):SLACK_CHANNEL_HOOK_URL}
      SENDGRID_API_KEY: ${file(./.env/${self:provider.stage}.json):SENDGRID_API_KEY}
      SENDGRID_ERROR_EMAIL_TEMPLATE_ID: ${file(./.env/${self:provider.stage}.json):SENDGRID_ERROR_EMAIL_TEMPLATE_ID}
      SENDGRID_EMAIL: ${file(./.env/${self:provider.stage}.json):SENDGRID_EMAIL}
plugins:
  - serverless-offline
  - serverless-esbuild
  # - serverless-custom-packaging-plugin
